# Generated by Django 5.2.11 on 2026-03-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rawmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='name',
            new_name='raw_material_name',
        ),
    ]
