# Generated by Django 5.2.11 on 2026-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_name_rawmaterial_raw_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_type_name', models.CharField(max_length=100)),
            ],
        ),
    ]
