# Generated by Django 5.2.11 on 2026-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_supplier_supplier_ordering_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_ordering_code',
            field=models.CharField(max_length=50),
        ),
    ]
