# Generated by Django 5.2.11 on 2026-03-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
    ]
