# Generated by Django 5.2.11 on 2026-03-25 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_field_is_deleted_fieldfixedvalue_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('joint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jointtype')),
                ('primary_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.field')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rawmaterial')),
                ('supplier1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier1', to='accounts.supplier')),
                ('supplier2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier2', to='accounts.supplier')),
            ],
        ),
    ]
