# Generated by Django 5.2.11 on 2026-03-25 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_toolcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='short_code',
            field=models.CharField(default='TEMP', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toolcode',
            name='supplier1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_supplier1', to='accounts.supplier'),
        ),
        migrations.AlterField(
            model_name='toolcode',
            name='supplier2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_supplier2', to='accounts.supplier'),
        ),
        migrations.CreateModel(
            name='ToolRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(blank=True, max_length=100)),
                ('supplier_code1', models.CharField(blank=True, max_length=100)),
                ('supplier_code2', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.field')),
                ('joint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jointtype')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rawmaterial')),
                ('supplier1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_supplier1', to='accounts.supplier')),
                ('supplier2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_supplier2', to='accounts.supplier')),
            ],
        ),
    ]
