# Generated by Django 5.2.11 on 2026-03-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_toolrequest_no_of_teeth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrequest',
            name='tool_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
