# Generated by Django 5.2.11 on 2026-03-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_toolrequest_tool_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrequest',
            name='fixed_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fieldfixedvalue'),
        ),
    ]
