# Generated by Django 5.2.11 on 2026-03-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jointtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_size_type', models.CharField(max_length=50)),
                ('field_size', models.IntegerField()),
                ('field_message', models.CharField(max_length=200)),
            ],
        ),
    ]
