# Generated by Django 5.2.11 on 2026-03-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_ordering_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
