# Generated by Django 5.2.11 on 2026-03-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_supplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='raw_material_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='FieldFixedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_value', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.field')),
            ],
        ),
    ]
