# Generated by Django 5.2.11 on 2026-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_rawmaterial_raw_material_name_fieldfixedvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldfixedvalue',
            name='explanation',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='fieldfixedvalue',
            name='fixed_value',
            field=models.CharField(max_length=200),
        ),
    ]
