# Generated by Django 5.2.11 on 2026-03-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_field_id_alter_fieldfixedvalue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
