# Generated by Django 5.2.11 on 2026-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_toolrequest_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrequest',
            name='bore_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='diameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='no_of_teeth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='overall_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
