# Generated by Django 5.2.11 on 2026-03-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_toolrequest_bore_size_toolrequest_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolrequest',
            name='no_of_teeth',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='overall_length',
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='boring_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='boring_teeth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='milling_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='milling_teeth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
