# Generated by Django 5.2.11 on 2026-04-01 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_toolrequest_fixed_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolrequest',
            name='bore_size',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='boring_length',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='boring_teeth',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='milling_length',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='milling_teeth',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='toolrequest',
            name='supplier2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_supplier2', to='accounts.supplier'),
        ),
        migrations.AlterField(
            model_name='toolrequest',
            name='tool_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='FieldAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=100)),
                ('input_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('select', 'Select (Fixed Values)')], default='number', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='accounts.field')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolRequestAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('field_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.fieldattribute')),
                ('tool_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='accounts.toolrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='ToolCode',
        ),
    ]
