# Generated by Django 5.2.11 on 2026-04-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_toolrequest_bore_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolrequestattribute',
            options={'ordering': ['field_attribute__order', 'field_attribute__id', 'id']},
        ),
        migrations.AlterField(
            model_name='toolrequestattribute',
            name='field_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fieldattribute'),
        ),
    ]
