# Generated by Django 5.2.11 on 2026-04-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_toolrequestattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldattribute',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
