# Generated by Django 5.2.11 on 2026-04-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_fieldattribute_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.fieldattribute')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
