# Generated by Django 5.2.11 on 2026-04-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_fieldattributeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldattributeoption',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
