# Generated by Django 5.2.11 on 2026-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_fieldattributeoption_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('can_access_tool_code', models.BooleanField(default=True, verbose_name='Tool Code Tab')),
                ('can_approve_requests', models.BooleanField(default=False, verbose_name='Can Approve Tool Codes')),
                ('can_access_master', models.BooleanField(default=False, verbose_name='Master Data Tab')),
                ('can_access_reports', models.BooleanField(default=False, verbose_name='Reports Tab')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='User Creation Tab')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='Role Master Tab')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
