# Generated by Django 5.2.11 on 2026-04-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_requests',
            field=models.BooleanField(default=True),
        ),
    ]
