# Generated by Django 5.2.11 on 2026-04-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_role_can_create_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrequest',
            name='joint_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jointtype'),
        ),
        migrations.AlterField(
            model_name='toolrequest',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='toolrequest',
            name='supplier1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_supplier1', to='accounts.supplier'),
        ),
    ]
