# Generated by Django 5.2.11 on 2026-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_toolrequest_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
